### ISSUE TITLE
Practice 6 - simple_local_planner - handling the goal point and distance to it

### ISSUE THREAD

**Issue by geopimik** [AnishShr/autoware_mini_practice#9]
1. I think you don't need `self.goal_point` It just adds complexity.

   - The only place where you actually use it is here
  https://github.com/AnishShr/autoware_mini_practice/blob/21d92c582d289c5f9fc24b477ca34f7889b10b66/practice_6/nodes/planning/local/simple_local_planner.py#L204-L206
   - But there you have `global_path_linestring` available and you could take the last coordinates from there.
   - So I would suggest removing all `goal_point` related things

2. And using the shapely `project` on local_path might not give you reasonable results. If the global path turns back and makes U-turn then the closest point to local path from the goal point, can be very close to ego vehicle, although the local path stretches 100m straight. 
![image](https://github.com/AnishShr/autoware_mini_practice/assets/33843059/1a0dd2e8-027c-45d8-b590-f561d5e5f2f5)

**Comment by AnishShr** [comment]
1. Removed variables `goal_point`, 'goal_coords', etc and took them from the `global_path_linestring`
2. Rather than projecting the goal point from local path, got the projected distances from global path and the projected distance of ego vehicle from global path start to get the distance between the ego vehicle and the goal.
https://github.com/AnishShr/autoware_mini_practice/blob/db7de2e51eb2ac93c232ab33cd755905c6f50521/practice_6/nodes/planning/local/simple_local_planner.py#L194

**Comment by AnishShr** [comment]
latest commit: https://github.com/AnishShr/autoware_mini_practice/commit/7d19ddadcd79e106cadf593cf4e87f63427ab2fd

**Comment by geopimik** [comment]
OK
